// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dashboard.proto

package dashboard

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ContentRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentRequest) Reset()         { *m = ContentRequest{} }
func (m *ContentRequest) String() string { return proto.CompactTextString(m) }
func (*ContentRequest) ProtoMessage()    {}
func (*ContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{1}
}

func (m *ContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentRequest.Unmarshal(m, b)
}
func (m *ContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentRequest.Marshal(b, m, deterministic)
}
func (m *ContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentRequest.Merge(m, src)
}
func (m *ContentRequest) XXX_Size() int {
	return xxx_messageInfo_ContentRequest.Size(m)
}
func (m *ContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContentRequest proto.InternalMessageInfo

func (m *ContentRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ContentResponse struct {
	ContentResponse      []byte   `protobuf:"bytes,1,opt,name=content_response,json=contentResponse,proto3" json:"content_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentResponse) Reset()         { *m = ContentResponse{} }
func (m *ContentResponse) String() string { return proto.CompactTextString(m) }
func (*ContentResponse) ProtoMessage()    {}
func (*ContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{2}
}

func (m *ContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentResponse.Unmarshal(m, b)
}
func (m *ContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentResponse.Marshal(b, m, deterministic)
}
func (m *ContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentResponse.Merge(m, src)
}
func (m *ContentResponse) XXX_Size() int {
	return xxx_messageInfo_ContentResponse.Size(m)
}
func (m *ContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContentResponse proto.InternalMessageInfo

func (m *ContentResponse) GetContentResponse() []byte {
	if m != nil {
		return m.ContentResponse
	}
	return nil
}

type HandleActionRequest struct {
	ActionName           string   `protobuf:"bytes,1,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleActionRequest) Reset()         { *m = HandleActionRequest{} }
func (m *HandleActionRequest) String() string { return proto.CompactTextString(m) }
func (*HandleActionRequest) ProtoMessage()    {}
func (*HandleActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{3}
}

func (m *HandleActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleActionRequest.Unmarshal(m, b)
}
func (m *HandleActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleActionRequest.Marshal(b, m, deterministic)
}
func (m *HandleActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleActionRequest.Merge(m, src)
}
func (m *HandleActionRequest) XXX_Size() int {
	return xxx_messageInfo_HandleActionRequest.Size(m)
}
func (m *HandleActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleActionRequest proto.InternalMessageInfo

func (m *HandleActionRequest) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *HandleActionRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type HandleActionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleActionResponse) Reset()         { *m = HandleActionResponse{} }
func (m *HandleActionResponse) String() string { return proto.CompactTextString(m) }
func (*HandleActionResponse) ProtoMessage()    {}
func (*HandleActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{4}
}

func (m *HandleActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleActionResponse.Unmarshal(m, b)
}
func (m *HandleActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleActionResponse.Marshal(b, m, deterministic)
}
func (m *HandleActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleActionResponse.Merge(m, src)
}
func (m *HandleActionResponse) XXX_Size() int {
	return xxx_messageInfo_HandleActionResponse.Size(m)
}
func (m *HandleActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleActionResponse proto.InternalMessageInfo

type NavigationRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NavigationRequest) Reset()         { *m = NavigationRequest{} }
func (m *NavigationRequest) String() string { return proto.CompactTextString(m) }
func (*NavigationRequest) ProtoMessage()    {}
func (*NavigationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{5}
}

func (m *NavigationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NavigationRequest.Unmarshal(m, b)
}
func (m *NavigationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NavigationRequest.Marshal(b, m, deterministic)
}
func (m *NavigationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NavigationRequest.Merge(m, src)
}
func (m *NavigationRequest) XXX_Size() int {
	return xxx_messageInfo_NavigationRequest.Size(m)
}
func (m *NavigationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NavigationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NavigationRequest proto.InternalMessageInfo

type NavigationResponse struct {
	Navigation           *NavigationResponse_Navigation `protobuf:"bytes,1,opt,name=navigation,proto3" json:"navigation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *NavigationResponse) Reset()         { *m = NavigationResponse{} }
func (m *NavigationResponse) String() string { return proto.CompactTextString(m) }
func (*NavigationResponse) ProtoMessage()    {}
func (*NavigationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{6}
}

func (m *NavigationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NavigationResponse.Unmarshal(m, b)
}
func (m *NavigationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NavigationResponse.Marshal(b, m, deterministic)
}
func (m *NavigationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NavigationResponse.Merge(m, src)
}
func (m *NavigationResponse) XXX_Size() int {
	return xxx_messageInfo_NavigationResponse.Size(m)
}
func (m *NavigationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NavigationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NavigationResponse proto.InternalMessageInfo

func (m *NavigationResponse) GetNavigation() *NavigationResponse_Navigation {
	if m != nil {
		return m.Navigation
	}
	return nil
}

type NavigationResponse_Navigation struct {
	Title                string                           `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Path                 string                           `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Children             []*NavigationResponse_Navigation `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	IconName             string                           `protobuf:"bytes,4,opt,name=icon_name,json=iconName,proto3" json:"icon_name,omitempty"`
	IconSource           string                           `protobuf:"bytes,5,opt,name=icon_source,json=iconSource,proto3" json:"icon_source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *NavigationResponse_Navigation) Reset()         { *m = NavigationResponse_Navigation{} }
func (m *NavigationResponse_Navigation) String() string { return proto.CompactTextString(m) }
func (*NavigationResponse_Navigation) ProtoMessage()    {}
func (*NavigationResponse_Navigation) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{6, 0}
}

func (m *NavigationResponse_Navigation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NavigationResponse_Navigation.Unmarshal(m, b)
}
func (m *NavigationResponse_Navigation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NavigationResponse_Navigation.Marshal(b, m, deterministic)
}
func (m *NavigationResponse_Navigation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NavigationResponse_Navigation.Merge(m, src)
}
func (m *NavigationResponse_Navigation) XXX_Size() int {
	return xxx_messageInfo_NavigationResponse_Navigation.Size(m)
}
func (m *NavigationResponse_Navigation) XXX_DiscardUnknown() {
	xxx_messageInfo_NavigationResponse_Navigation.DiscardUnknown(m)
}

var xxx_messageInfo_NavigationResponse_Navigation proto.InternalMessageInfo

func (m *NavigationResponse_Navigation) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NavigationResponse_Navigation) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *NavigationResponse_Navigation) GetChildren() []*NavigationResponse_Navigation {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *NavigationResponse_Navigation) GetIconName() string {
	if m != nil {
		return m.IconName
	}
	return ""
}

func (m *NavigationResponse_Navigation) GetIconSource() string {
	if m != nil {
		return m.IconSource
	}
	return ""
}

type RegisterRequest struct {
	DashboardAPIAddress  string   `protobuf:"bytes,1,opt,name=dashboardAPIAddress,proto3" json:"dashboardAPIAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{7}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetDashboardAPIAddress() string {
	if m != nil {
		return m.DashboardAPIAddress
	}
	return ""
}

type RegisterResponse struct {
	PluginName           string                         `protobuf:"bytes,1,opt,name=pluginName,proto3" json:"pluginName,omitempty"`
	Description          string                         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Capabilities         *RegisterResponse_Capabilities `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{8}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *RegisterResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RegisterResponse) GetCapabilities() *RegisterResponse_Capabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

type RegisterResponse_GroupVersionKind struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind                 string   `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse_GroupVersionKind) Reset()         { *m = RegisterResponse_GroupVersionKind{} }
func (m *RegisterResponse_GroupVersionKind) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse_GroupVersionKind) ProtoMessage()    {}
func (*RegisterResponse_GroupVersionKind) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{8, 0}
}

func (m *RegisterResponse_GroupVersionKind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse_GroupVersionKind.Unmarshal(m, b)
}
func (m *RegisterResponse_GroupVersionKind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse_GroupVersionKind.Marshal(b, m, deterministic)
}
func (m *RegisterResponse_GroupVersionKind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse_GroupVersionKind.Merge(m, src)
}
func (m *RegisterResponse_GroupVersionKind) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse_GroupVersionKind.Size(m)
}
func (m *RegisterResponse_GroupVersionKind) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse_GroupVersionKind.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse_GroupVersionKind proto.InternalMessageInfo

func (m *RegisterResponse_GroupVersionKind) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *RegisterResponse_GroupVersionKind) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RegisterResponse_GroupVersionKind) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

type RegisterResponse_Capabilities struct {
	SupportsPrinterConfig []*RegisterResponse_GroupVersionKind `protobuf:"bytes,1,rep,name=supportsPrinterConfig,proto3" json:"supportsPrinterConfig,omitempty"`
	SupportsPrinterStatus []*RegisterResponse_GroupVersionKind `protobuf:"bytes,2,rep,name=supportsPrinterStatus,proto3" json:"supportsPrinterStatus,omitempty"`
	SupportsPrinterItems  []*RegisterResponse_GroupVersionKind `protobuf:"bytes,3,rep,name=supportsPrinterItems,proto3" json:"supportsPrinterItems,omitempty"`
	SupportsObjectStatus  []*RegisterResponse_GroupVersionKind `protobuf:"bytes,4,rep,name=supportsObjectStatus,proto3" json:"supportsObjectStatus,omitempty"`
	SupportsTab           []*RegisterResponse_GroupVersionKind `protobuf:"bytes,5,rep,name=supportsTab,proto3" json:"supportsTab,omitempty"`
	IsModule              bool                                 `protobuf:"varint,6,opt,name=isModule,proto3" json:"isModule,omitempty"`
	ActionNames           []string                             `protobuf:"bytes,7,rep,name=action_names,json=actionNames,proto3" json:"action_names,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                             `json:"-"`
	XXX_unrecognized      []byte                               `json:"-"`
	XXX_sizecache         int32                                `json:"-"`
}

func (m *RegisterResponse_Capabilities) Reset()         { *m = RegisterResponse_Capabilities{} }
func (m *RegisterResponse_Capabilities) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse_Capabilities) ProtoMessage()    {}
func (*RegisterResponse_Capabilities) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{8, 1}
}

func (m *RegisterResponse_Capabilities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse_Capabilities.Unmarshal(m, b)
}
func (m *RegisterResponse_Capabilities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse_Capabilities.Marshal(b, m, deterministic)
}
func (m *RegisterResponse_Capabilities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse_Capabilities.Merge(m, src)
}
func (m *RegisterResponse_Capabilities) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse_Capabilities.Size(m)
}
func (m *RegisterResponse_Capabilities) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse_Capabilities.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse_Capabilities proto.InternalMessageInfo

func (m *RegisterResponse_Capabilities) GetSupportsPrinterConfig() []*RegisterResponse_GroupVersionKind {
	if m != nil {
		return m.SupportsPrinterConfig
	}
	return nil
}

func (m *RegisterResponse_Capabilities) GetSupportsPrinterStatus() []*RegisterResponse_GroupVersionKind {
	if m != nil {
		return m.SupportsPrinterStatus
	}
	return nil
}

func (m *RegisterResponse_Capabilities) GetSupportsPrinterItems() []*RegisterResponse_GroupVersionKind {
	if m != nil {
		return m.SupportsPrinterItems
	}
	return nil
}

func (m *RegisterResponse_Capabilities) GetSupportsObjectStatus() []*RegisterResponse_GroupVersionKind {
	if m != nil {
		return m.SupportsObjectStatus
	}
	return nil
}

func (m *RegisterResponse_Capabilities) GetSupportsTab() []*RegisterResponse_GroupVersionKind {
	if m != nil {
		return m.SupportsTab
	}
	return nil
}

func (m *RegisterResponse_Capabilities) GetIsModule() bool {
	if m != nil {
		return m.IsModule
	}
	return false
}

func (m *RegisterResponse_Capabilities) GetActionNames() []string {
	if m != nil {
		return m.ActionNames
	}
	return nil
}

type ObjectRequest struct {
	Object               []byte   `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectRequest) Reset()         { *m = ObjectRequest{} }
func (m *ObjectRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectRequest) ProtoMessage()    {}
func (*ObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{9}
}

func (m *ObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectRequest.Unmarshal(m, b)
}
func (m *ObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectRequest.Marshal(b, m, deterministic)
}
func (m *ObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectRequest.Merge(m, src)
}
func (m *ObjectRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectRequest.Size(m)
}
func (m *ObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectRequest proto.InternalMessageInfo

func (m *ObjectRequest) GetObject() []byte {
	if m != nil {
		return m.Object
	}
	return nil
}

type PrintResponse struct {
	Config               []*PrintResponse_SummaryItem `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty"`
	Status               []*PrintResponse_SummaryItem `protobuf:"bytes,2,rep,name=status,proto3" json:"status,omitempty"`
	Items                []byte                       `protobuf:"bytes,3,opt,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *PrintResponse) Reset()         { *m = PrintResponse{} }
func (m *PrintResponse) String() string { return proto.CompactTextString(m) }
func (*PrintResponse) ProtoMessage()    {}
func (*PrintResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{10}
}

func (m *PrintResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrintResponse.Unmarshal(m, b)
}
func (m *PrintResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrintResponse.Marshal(b, m, deterministic)
}
func (m *PrintResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrintResponse.Merge(m, src)
}
func (m *PrintResponse) XXX_Size() int {
	return xxx_messageInfo_PrintResponse.Size(m)
}
func (m *PrintResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrintResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrintResponse proto.InternalMessageInfo

func (m *PrintResponse) GetConfig() []*PrintResponse_SummaryItem {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *PrintResponse) GetStatus() []*PrintResponse_SummaryItem {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *PrintResponse) GetItems() []byte {
	if m != nil {
		return m.Items
	}
	return nil
}

type PrintResponse_SummaryItem struct {
	Header               string   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Component            []byte   `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrintResponse_SummaryItem) Reset()         { *m = PrintResponse_SummaryItem{} }
func (m *PrintResponse_SummaryItem) String() string { return proto.CompactTextString(m) }
func (*PrintResponse_SummaryItem) ProtoMessage()    {}
func (*PrintResponse_SummaryItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{10, 0}
}

func (m *PrintResponse_SummaryItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrintResponse_SummaryItem.Unmarshal(m, b)
}
func (m *PrintResponse_SummaryItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrintResponse_SummaryItem.Marshal(b, m, deterministic)
}
func (m *PrintResponse_SummaryItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrintResponse_SummaryItem.Merge(m, src)
}
func (m *PrintResponse_SummaryItem) XXX_Size() int {
	return xxx_messageInfo_PrintResponse_SummaryItem.Size(m)
}
func (m *PrintResponse_SummaryItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PrintResponse_SummaryItem.DiscardUnknown(m)
}

var xxx_messageInfo_PrintResponse_SummaryItem proto.InternalMessageInfo

func (m *PrintResponse_SummaryItem) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *PrintResponse_SummaryItem) GetComponent() []byte {
	if m != nil {
		return m.Component
	}
	return nil
}

type PrintTabResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Layout               []byte   `protobuf:"bytes,2,opt,name=layout,proto3" json:"layout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrintTabResponse) Reset()         { *m = PrintTabResponse{} }
func (m *PrintTabResponse) String() string { return proto.CompactTextString(m) }
func (*PrintTabResponse) ProtoMessage()    {}
func (*PrintTabResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{11}
}

func (m *PrintTabResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrintTabResponse.Unmarshal(m, b)
}
func (m *PrintTabResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrintTabResponse.Marshal(b, m, deterministic)
}
func (m *PrintTabResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrintTabResponse.Merge(m, src)
}
func (m *PrintTabResponse) XXX_Size() int {
	return xxx_messageInfo_PrintTabResponse.Size(m)
}
func (m *PrintTabResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrintTabResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrintTabResponse proto.InternalMessageInfo

func (m *PrintTabResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PrintTabResponse) GetLayout() []byte {
	if m != nil {
		return m.Layout
	}
	return nil
}

type ObjectStatusResponse struct {
	ObjectStatus         []byte   `protobuf:"bytes,1,opt,name=objectStatus,proto3" json:"objectStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectStatusResponse) Reset()         { *m = ObjectStatusResponse{} }
func (m *ObjectStatusResponse) String() string { return proto.CompactTextString(m) }
func (*ObjectStatusResponse) ProtoMessage()    {}
func (*ObjectStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{12}
}

func (m *ObjectStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectStatusResponse.Unmarshal(m, b)
}
func (m *ObjectStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectStatusResponse.Marshal(b, m, deterministic)
}
func (m *ObjectStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectStatusResponse.Merge(m, src)
}
func (m *ObjectStatusResponse) XXX_Size() int {
	return xxx_messageInfo_ObjectStatusResponse.Size(m)
}
func (m *ObjectStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectStatusResponse proto.InternalMessageInfo

func (m *ObjectStatusResponse) GetObjectStatus() []byte {
	if m != nil {
		return m.ObjectStatus
	}
	return nil
}

type WatchRequest struct {
	WatchID              string   `protobuf:"bytes,1,opt,name=watchID,proto3" json:"watchID,omitempty"`
	Object               []byte   `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchRequest) Reset()         { *m = WatchRequest{} }
func (m *WatchRequest) String() string { return proto.CompactTextString(m) }
func (*WatchRequest) ProtoMessage()    {}
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b97678da3a35dfb, []int{13}
}

func (m *WatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchRequest.Unmarshal(m, b)
}
func (m *WatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchRequest.Marshal(b, m, deterministic)
}
func (m *WatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchRequest.Merge(m, src)
}
func (m *WatchRequest) XXX_Size() int {
	return xxx_messageInfo_WatchRequest.Size(m)
}
func (m *WatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchRequest proto.InternalMessageInfo

func (m *WatchRequest) GetWatchID() string {
	if m != nil {
		return m.WatchID
	}
	return ""
}

func (m *WatchRequest) GetObject() []byte {
	if m != nil {
		return m.Object
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "dashboard.Empty")
	proto.RegisterType((*ContentRequest)(nil), "dashboard.ContentRequest")
	proto.RegisterType((*ContentResponse)(nil), "dashboard.ContentResponse")
	proto.RegisterType((*HandleActionRequest)(nil), "dashboard.HandleActionRequest")
	proto.RegisterType((*HandleActionResponse)(nil), "dashboard.HandleActionResponse")
	proto.RegisterType((*NavigationRequest)(nil), "dashboard.NavigationRequest")
	proto.RegisterType((*NavigationResponse)(nil), "dashboard.NavigationResponse")
	proto.RegisterType((*NavigationResponse_Navigation)(nil), "dashboard.NavigationResponse.Navigation")
	proto.RegisterType((*RegisterRequest)(nil), "dashboard.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "dashboard.RegisterResponse")
	proto.RegisterType((*RegisterResponse_GroupVersionKind)(nil), "dashboard.RegisterResponse.GroupVersionKind")
	proto.RegisterType((*RegisterResponse_Capabilities)(nil), "dashboard.RegisterResponse.Capabilities")
	proto.RegisterType((*ObjectRequest)(nil), "dashboard.ObjectRequest")
	proto.RegisterType((*PrintResponse)(nil), "dashboard.PrintResponse")
	proto.RegisterType((*PrintResponse_SummaryItem)(nil), "dashboard.PrintResponse.SummaryItem")
	proto.RegisterType((*PrintTabResponse)(nil), "dashboard.PrintTabResponse")
	proto.RegisterType((*ObjectStatusResponse)(nil), "dashboard.ObjectStatusResponse")
	proto.RegisterType((*WatchRequest)(nil), "dashboard.WatchRequest")
}

func init() { proto.RegisterFile("dashboard.proto", fileDescriptor_9b97678da3a35dfb) }

var fileDescriptor_9b97678da3a35dfb = []byte{
	// 878 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdb, 0x6e, 0xf3, 0x44,
	0x10, 0x56, 0xce, 0xc9, 0xc4, 0x3f, 0x09, 0xdb, 0xf0, 0x63, 0xdc, 0xd2, 0x04, 0xab, 0x12, 0x45,
	0x42, 0x11, 0x2a, 0x42, 0x42, 0x50, 0xa1, 0x46, 0x29, 0xa2, 0x11, 0xd0, 0x46, 0x6e, 0x29, 0x97,
	0x65, 0x63, 0x2f, 0xc9, 0x82, 0xe3, 0x35, 0xde, 0x75, 0x51, 0x9e, 0x85, 0x2b, 0x6e, 0x90, 0x78,
	0x05, 0x1e, 0x88, 0xe7, 0x40, 0x5e, 0xaf, 0x9d, 0x75, 0x9a, 0x44, 0xb4, 0x70, 0xe7, 0xf9, 0x76,
	0xe6, 0x9b, 0xd9, 0x39, 0xec, 0x18, 0x3a, 0x1e, 0xe6, 0x8b, 0x19, 0xc3, 0x91, 0x37, 0x0c, 0x23,
	0x26, 0x18, 0x6a, 0xe5, 0x80, 0xdd, 0x80, 0xda, 0x97, 0xcb, 0x50, 0xac, 0xec, 0x13, 0x78, 0x63,
	0xcc, 0x02, 0x41, 0x02, 0xe1, 0x90, 0x5f, 0x62, 0xc2, 0x05, 0x42, 0x50, 0x0d, 0xb1, 0x58, 0x98,
	0xa5, 0x41, 0xe9, 0xb4, 0xe5, 0xc8, 0x6f, 0xfb, 0x1c, 0x3a, 0xb9, 0x16, 0x0f, 0x59, 0xc0, 0x09,
	0xfa, 0x00, 0xba, 0x6e, 0x0a, 0x3d, 0x44, 0x0a, 0x93, 0x26, 0x86, 0xd3, 0x71, 0x8b, 0xaa, 0xf6,
	0x14, 0x0e, 0xae, 0x70, 0xe0, 0xf9, 0x64, 0xe4, 0x0a, 0xca, 0x82, 0xcc, 0x51, 0x1f, 0xda, 0x58,
	0x02, 0x0f, 0x01, 0x5e, 0x12, 0xe5, 0x0f, 0x52, 0xe8, 0x1a, 0x2f, 0x09, 0x32, 0xa1, 0x11, 0xe2,
	0x95, 0xcf, 0xb0, 0x67, 0x96, 0x25, 0x73, 0x26, 0xda, 0xaf, 0xa1, 0x57, 0x64, 0x54, 0x9e, 0x0e,
	0xe0, 0xcd, 0x6b, 0xfc, 0x48, 0xe7, 0x58, 0xf3, 0x63, 0xff, 0x56, 0x06, 0xa4, 0xa3, 0xea, 0x02,
	0x57, 0x00, 0x41, 0x8e, 0x4a, 0xef, 0xed, 0xb3, 0xd3, 0xe1, 0x3a, 0x67, 0x4f, 0x4d, 0x74, 0x48,
	0xb3, 0xb5, 0xfe, 0x2a, 0x01, 0xac, 0x8f, 0x50, 0x0f, 0x6a, 0x82, 0x0a, 0x3f, 0xbb, 0x51, 0x2a,
	0xe4, 0x69, 0x2d, 0xaf, 0xd3, 0x8a, 0x2e, 0xa1, 0xe9, 0x2e, 0xa8, 0xef, 0x45, 0x24, 0x30, 0x2b,
	0x83, 0xca, 0xb3, 0x02, 0xc8, 0x2d, 0xd1, 0x21, 0xb4, 0xa8, 0x9b, 0x65, 0xb1, 0x2a, 0xe9, 0x9b,
	0x09, 0x20, 0x73, 0xd8, 0x87, 0xb6, 0x3c, 0xe4, 0x2c, 0x8e, 0x5c, 0x62, 0xd6, 0xd2, 0x24, 0x27,
	0xd0, 0xad, 0x44, 0xec, 0x31, 0x74, 0x1c, 0x32, 0xa7, 0x5c, 0x90, 0x28, 0x2b, 0xcc, 0x47, 0x70,
	0x90, 0x47, 0x31, 0x9a, 0x4e, 0x46, 0x9e, 0x17, 0x11, 0xce, 0xd5, 0x75, 0xb6, 0x1d, 0xd9, 0x7f,
	0xd4, 0xa1, 0xbb, 0x66, 0x51, 0x09, 0x3e, 0x06, 0x08, 0xfd, 0x78, 0x4e, 0x65, 0x20, 0x59, 0x79,
	0xd7, 0x08, 0x1a, 0x40, 0xdb, 0x23, 0xdc, 0x8d, 0x68, 0x28, 0x2b, 0x90, 0x26, 0x46, 0x87, 0xd0,
	0x37, 0x60, 0xb8, 0x38, 0xc4, 0x33, 0xea, 0x53, 0x41, 0x09, 0x37, 0x2b, 0x4f, 0x8a, 0xb4, 0xe9,
	0x74, 0x38, 0xd6, 0xf4, 0x9d, 0x82, 0xb5, 0x75, 0x0f, 0xdd, 0xaf, 0x22, 0x16, 0x87, 0xf7, 0x24,
	0xe2, 0x94, 0x05, 0x5f, 0xd3, 0xc0, 0x4b, 0x6a, 0x35, 0x4f, 0xb0, 0xac, 0x56, 0x52, 0x48, 0x1a,
	0xef, 0x31, 0x55, 0x52, 0x51, 0x65, 0x62, 0x52, 0xc5, 0x9f, 0x69, 0xe0, 0xc9, 0x48, 0x5a, 0x8e,
	0xfc, 0xb6, 0xfe, 0xac, 0x82, 0xa1, 0xbb, 0x45, 0x33, 0x78, 0x8b, 0xc7, 0x61, 0xc8, 0x22, 0xc1,
	0xa7, 0x11, 0x0d, 0x04, 0x89, 0xc6, 0x2c, 0xf8, 0x91, 0xce, 0xcd, 0x92, 0xac, 0xf1, 0x87, 0xfb,
	0xe2, 0xdf, 0x8c, 0xd0, 0xd9, 0x4e, 0xb5, 0xc5, 0xc7, 0xad, 0xc0, 0x22, 0xe6, 0x66, 0xf9, 0x7f,
	0xf0, 0x91, 0x52, 0xa1, 0x1f, 0xa0, 0xb7, 0x71, 0x30, 0x11, 0x64, 0xc9, 0x55, 0xab, 0x3e, 0xcf,
	0xc5, 0x56, 0x26, 0xdd, 0xc3, 0xcd, 0xec, 0x27, 0xe2, 0x0a, 0x75, 0x89, 0xea, 0x7f, 0xf1, 0xa0,
	0x33, 0xa1, 0x6b, 0x68, 0x67, 0xf8, 0x1d, 0x9e, 0x99, 0xb5, 0x17, 0x10, 0xeb, 0x04, 0xc8, 0x82,
	0x26, 0xe5, 0xdf, 0x32, 0x2f, 0xf6, 0x89, 0x59, 0x1f, 0x94, 0x4e, 0x9b, 0x4e, 0x2e, 0xa3, 0xf7,
	0xc0, 0xd0, 0x1e, 0x34, 0x6e, 0x36, 0x06, 0x95, 0xa4, 0xa3, 0xd7, 0x2f, 0x1a, 0xb7, 0xdf, 0x87,
	0x57, 0x69, 0x78, 0xd9, 0xac, 0xbd, 0x86, 0x3a, 0x93, 0x80, 0x7a, 0x3c, 0x95, 0x64, 0xff, 0x5d,
	0x82, 0x57, 0x32, 0x55, 0xf9, 0x38, 0x9d, 0x43, 0xdd, 0xd5, 0xdb, 0xe8, 0x44, 0xbb, 0x44, 0x41,
	0x73, 0x78, 0x1b, 0x2f, 0x97, 0x38, 0x5a, 0x25, 0x29, 0x76, 0x94, 0x4d, 0x62, 0xcd, 0xf5, 0x06,
	0xf9, 0x97, 0xd6, 0xa9, 0x4d, 0x32, 0x26, 0x54, 0x95, 0x3e, 0x09, 0x32, 0x15, 0xac, 0x31, 0xb4,
	0x35, 0xe5, 0xe4, 0x2a, 0x0b, 0x82, 0x3d, 0x12, 0xa9, 0x61, 0x52, 0x12, 0x3a, 0x82, 0x96, 0xcb,
	0x96, 0x21, 0x0b, 0x48, 0x20, 0xd4, 0x43, 0xbe, 0x06, 0xec, 0x2f, 0xa0, 0x2b, 0xfd, 0xdf, 0xe1,
	0x59, 0x7e, 0x55, 0x04, 0x55, 0x6d, 0x25, 0xc8, 0xef, 0x84, 0xdd, 0xc7, 0x2b, 0x16, 0x67, 0x14,
	0x4a, 0xb2, 0x3f, 0x83, 0x9e, 0x5e, 0xf0, 0x9c, 0xc3, 0x06, 0x83, 0xe9, 0x2d, 0x95, 0xa6, 0xb7,
	0x80, 0xd9, 0x17, 0x60, 0x7c, 0x8f, 0x85, 0xbb, 0xc8, 0x8a, 0x61, 0x42, 0xe3, 0xd7, 0x44, 0x9e,
	0x5c, 0x2a, 0xd7, 0x99, 0xa8, 0x95, 0xa9, 0xac, 0x97, 0xe9, 0xec, 0xf7, 0x1a, 0xd4, 0xa7, 0xf2,
	0x49, 0x43, 0x17, 0xd0, 0x50, 0x3b, 0x12, 0xbd, 0xa3, 0x25, 0xb7, 0xb8, 0x5d, 0x2d, 0x6b, 0xdb,
	0x91, 0x0a, 0xf9, 0x06, 0x0c, 0x7d, 0xab, 0xa1, 0x63, 0x4d, 0x77, 0xcb, 0x02, 0xb5, 0xfa, 0x3b,
	0xcf, 0x15, 0xe1, 0xa4, 0xb0, 0x97, 0x8e, 0x76, 0xec, 0x96, 0x94, 0xec, 0xdd, 0xbd, 0x9b, 0x07,
	0x8d, 0xa1, 0x99, 0x4d, 0x0a, 0xb2, 0xb6, 0x8e, 0x4f, 0x4a, 0x73, 0xb8, 0x67, 0xb4, 0xd0, 0xe7,
	0x50, 0x93, 0xb5, 0x46, 0xa6, 0xa6, 0x55, 0x98, 0x07, 0xcb, 0xdc, 0xd5, 0x97, 0x68, 0x02, 0x46,
	0x61, 0xb2, 0x77, 0x73, 0xf4, 0x9f, 0x9c, 0x6c, 0xf4, 0xc6, 0x08, 0x9a, 0x59, 0xcf, 0xed, 0xa1,
	0x39, 0xdc, 0x0c, 0x45, 0x6f, 0xd1, 0x4f, 0xa0, 0x29, 0x5b, 0x67, 0xe4, 0x79, 0xe8, 0x6d, 0x4d,
	0x51, 0xef, 0x27, 0xab, 0xab, 0x1d, 0xc8, 0xdf, 0x2d, 0xf4, 0x29, 0xb4, 0xa5, 0xc6, 0x77, 0xa1,
	0x87, 0x05, 0x79, 0x89, 0xe5, 0x25, 0xf1, 0xc9, 0xb3, 0x2c, 0x67, 0x75, 0xf9, 0xf7, 0xf7, 0xf1,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x4a, 0x08, 0xcc, 0x10, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginClient interface {
	Content(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*ContentResponse, error)
	HandleAction(ctx context.Context, in *HandleActionRequest, opts ...grpc.CallOption) (*HandleActionResponse, error)
	Navigation(ctx context.Context, in *NavigationRequest, opts ...grpc.CallOption) (*NavigationResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Print(ctx context.Context, in *ObjectRequest, opts ...grpc.CallOption) (*PrintResponse, error)
	ObjectStatus(ctx context.Context, in *ObjectRequest, opts ...grpc.CallOption) (*ObjectStatusResponse, error)
	PrintTab(ctx context.Context, in *ObjectRequest, opts ...grpc.CallOption) (*PrintTabResponse, error)
	WatchAdd(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*Empty, error)
	WatchUpdate(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*Empty, error)
	WatchDelete(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*Empty, error)
}

type pluginClient struct {
	cc *grpc.ClientConn
}

func NewPluginClient(cc *grpc.ClientConn) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) Content(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*ContentResponse, error) {
	out := new(ContentResponse)
	err := c.cc.Invoke(ctx, "/dashboard.Plugin/Content", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) HandleAction(ctx context.Context, in *HandleActionRequest, opts ...grpc.CallOption) (*HandleActionResponse, error) {
	out := new(HandleActionResponse)
	err := c.cc.Invoke(ctx, "/dashboard.Plugin/HandleAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Navigation(ctx context.Context, in *NavigationRequest, opts ...grpc.CallOption) (*NavigationResponse, error) {
	out := new(NavigationResponse)
	err := c.cc.Invoke(ctx, "/dashboard.Plugin/Navigation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/dashboard.Plugin/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Print(ctx context.Context, in *ObjectRequest, opts ...grpc.CallOption) (*PrintResponse, error) {
	out := new(PrintResponse)
	err := c.cc.Invoke(ctx, "/dashboard.Plugin/Print", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) ObjectStatus(ctx context.Context, in *ObjectRequest, opts ...grpc.CallOption) (*ObjectStatusResponse, error) {
	out := new(ObjectStatusResponse)
	err := c.cc.Invoke(ctx, "/dashboard.Plugin/ObjectStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) PrintTab(ctx context.Context, in *ObjectRequest, opts ...grpc.CallOption) (*PrintTabResponse, error) {
	out := new(PrintTabResponse)
	err := c.cc.Invoke(ctx, "/dashboard.Plugin/PrintTab", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) WatchAdd(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/dashboard.Plugin/WatchAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) WatchUpdate(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/dashboard.Plugin/WatchUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) WatchDelete(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/dashboard.Plugin/WatchDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
type PluginServer interface {
	Content(context.Context, *ContentRequest) (*ContentResponse, error)
	HandleAction(context.Context, *HandleActionRequest) (*HandleActionResponse, error)
	Navigation(context.Context, *NavigationRequest) (*NavigationResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Print(context.Context, *ObjectRequest) (*PrintResponse, error)
	ObjectStatus(context.Context, *ObjectRequest) (*ObjectStatusResponse, error)
	PrintTab(context.Context, *ObjectRequest) (*PrintTabResponse, error)
	WatchAdd(context.Context, *WatchRequest) (*Empty, error)
	WatchUpdate(context.Context, *WatchRequest) (*Empty, error)
	WatchDelete(context.Context, *WatchRequest) (*Empty, error)
}

// UnimplementedPluginServer can be embedded to have forward compatible implementations.
type UnimplementedPluginServer struct {
}

func (*UnimplementedPluginServer) Content(ctx context.Context, req *ContentRequest) (*ContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Content not implemented")
}
func (*UnimplementedPluginServer) HandleAction(ctx context.Context, req *HandleActionRequest) (*HandleActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleAction not implemented")
}
func (*UnimplementedPluginServer) Navigation(ctx context.Context, req *NavigationRequest) (*NavigationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Navigation not implemented")
}
func (*UnimplementedPluginServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedPluginServer) Print(ctx context.Context, req *ObjectRequest) (*PrintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Print not implemented")
}
func (*UnimplementedPluginServer) ObjectStatus(ctx context.Context, req *ObjectRequest) (*ObjectStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObjectStatus not implemented")
}
func (*UnimplementedPluginServer) PrintTab(ctx context.Context, req *ObjectRequest) (*PrintTabResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintTab not implemented")
}
func (*UnimplementedPluginServer) WatchAdd(ctx context.Context, req *WatchRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WatchAdd not implemented")
}
func (*UnimplementedPluginServer) WatchUpdate(ctx context.Context, req *WatchRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WatchUpdate not implemented")
}
func (*UnimplementedPluginServer) WatchDelete(ctx context.Context, req *WatchRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WatchDelete not implemented")
}

func RegisterPluginServer(s *grpc.Server, srv PluginServer) {
	s.RegisterService(&_Plugin_serviceDesc, srv)
}

func _Plugin_Content_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Content(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Plugin/Content",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Content(ctx, req.(*ContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_HandleAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).HandleAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Plugin/HandleAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).HandleAction(ctx, req.(*HandleActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Navigation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NavigationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Navigation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Plugin/Navigation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Navigation(ctx, req.(*NavigationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Plugin/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Print_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Print(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Plugin/Print",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Print(ctx, req.(*ObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_ObjectStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).ObjectStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Plugin/ObjectStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).ObjectStatus(ctx, req.(*ObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_PrintTab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).PrintTab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Plugin/PrintTab",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).PrintTab(ctx, req.(*ObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_WatchAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).WatchAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Plugin/WatchAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).WatchAdd(ctx, req.(*WatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_WatchUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).WatchUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Plugin/WatchUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).WatchUpdate(ctx, req.(*WatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_WatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).WatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.Plugin/WatchDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).WatchDelete(ctx, req.(*WatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Content",
			Handler:    _Plugin_Content_Handler,
		},
		{
			MethodName: "HandleAction",
			Handler:    _Plugin_HandleAction_Handler,
		},
		{
			MethodName: "Navigation",
			Handler:    _Plugin_Navigation_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Plugin_Register_Handler,
		},
		{
			MethodName: "Print",
			Handler:    _Plugin_Print_Handler,
		},
		{
			MethodName: "ObjectStatus",
			Handler:    _Plugin_ObjectStatus_Handler,
		},
		{
			MethodName: "PrintTab",
			Handler:    _Plugin_PrintTab_Handler,
		},
		{
			MethodName: "WatchAdd",
			Handler:    _Plugin_WatchAdd_Handler,
		},
		{
			MethodName: "WatchUpdate",
			Handler:    _Plugin_WatchUpdate_Handler,
		},
		{
			MethodName: "WatchDelete",
			Handler:    _Plugin_WatchDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dashboard.proto",
}
