---
kind: pipeline
name: octant

workspace:
  base: /go
  path: src/github.com/vmware/octant

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
  - name: frontend
    image: sfoo/node-chrome:0.0.2
    commands:
      - cd web
      - npm ci
      - npm run-script build
      - npm run lint
      - npm run test:headless
  - name: backend
    image: golang:1.13
    environment:
      GOFLAGS: -mod=vendor
      GO111MODULE: on
    commands:
      - make go-install
      - make test
      - go generate ./web
      - make vet
    depends_on:
    - frontend
  - name: build
    image: golang:1.13
    environment:
      CGO_ENABLED: 0
    commands:
      - make octant-dev
    depends_on:
    - frontend
    - backend

---
kind: pipeline
name: nightly

trigger:
  cron: [ nightly ]

workspace:
  base: /go
  path: src/github.com/vmware/octant

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
  - name: releaser
    environment:
      GOOGLE_APPLICATION_JSON:
        from_secret: google_application_json
    image: goreleaser/goreleaser:v0.119-cgo
    commands:
      - echo "$GOOGLE_APPLICATION_JSON" | base64 -d > /tmp/gs.json
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gs.json goreleaser -f .goreleaser-nightly.yml --rm-dist --skip-validate

depends_on:
  - octant

---
kind: pipeline
name: release

trigger:
  event:
  - tag

workspace:
  base: /go
  path: src/github.com/vmware/octant

steps:
  - name: releaser
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    image: goreleaser/goreleaser:v0.113-cgo
    commands:
      - ci/drone-deploy.sh

depends_on:
  - octant

---
kind: signature
hmac: fc3c8c31897d98fc7b9eed31a5bf5bda0f3f8c9096b6b7636b669a931c474c05

...
