{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "octant.serviceAccountName" . }}
  labels:
{{ include "octant.labels" . | indent 4 }}
{{- end -}}
