apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
  labels:
    project: dev-dashboard
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
