# Copyright (c) 2019 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: example-secret
type: generic
data:
  API_KEY: bm90aGluZ3Rvc2VlaGVyZQ==
