# Copyright (c) 2019 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: batch/v1
kind: Job
metadata:
  generateName: job-fail-
  labels:
    octant-scenario: failed-job
spec:
  template:
    spec:
      containers:
      - name: executor
        image: busybox
        command: ["sh", "-c", "sleep 5; echo 'job fail'; exit 1"]
      restartPolicy: Never
