const exampleDate = new Date('Wed Jun 26 2019 18:34:05 GMT-0400 (Eastern Daylight Time)');
;

export default [
  {
    currentStack: 'olympusstackA',
    stackOptions: ['olympusstackA', 'releaseChannelB', 'olympusstackC'],
    channelFollowing: 'unstable',
    workloads: [
      {
        name: 'ui',
        isPinned: true,
        lastUpdated: exampleDate,
        revision: '2f2932c83b7a401d960f4538bf787e12c44dfd666',
        sourceImage: 'sourceImageA',
      },
      {
        name: 'cluster-health',
        isFollowingChannel: true,
        channelFollowing: 'unstable',
        lastUpdated: exampleDate,
        revision: 'b90s232c83b7a401d960f4538bf787e12c44dfd666',
        sourceImage: 'sourceImageB',
      },
      {
        name: 'resource manager',
        isFollowingChannel: true,
        channelFollowing: 'unstable',
        lastUpdated: exampleDate,
        revision: 'b90s232c83b7a401d960f4538bf787e12c44dfd666',
        sourceImage: 'sourceImageB',
      },
      {
        name: 'cluster-service',
        isFollowingChannel: true,
        channelFollowing: 'unstable',
        lastUpdated: exampleDate,
        revision: 'b90s232c83b7a401d960f4538bf787e12c44dfd666',
        sourceImage: 'sourceImageB',
      },
      {
        name: 'extension-catalog-service',
        isFollowingChannel: true,
        channelFollowing: 'unstable',
        lastUpdated: exampleDate,
        revision: 'b90s232c83b7a401d960f4538bf787e12c44dfd666',
        sourceImage: 'sourceImageB',
      },
      {
        name: 'cluster-agent-service',
        isFollowingChannel: true,
        channelFollowing: 'unstable',
        lastUpdated: exampleDate,
        revision: 'b90s232c83b7a401d960f4538bf787e12c44dfd666',
        sourceImage: 'sourceImageB',
      },
      {
        name: 'intent',
        isFollowingChannel: true,
        channelFollowing: 'unstable',
        lastUpdated: exampleDate,
        revision: 'b90s232c83b7a401d960f4538bf787e12c44dfd666',
        sourceImage: 'sourceImageB',
      },
    ],
  },
  {
    currentStack: 'releaseChannelB',
    stackOptions: ['olympusstackA', 'releaseChannelB', 'olympusstackC'],
    channelFollowing: 'testing',
    workloads: [
      {
        name: 'ui',
        isPinned: true,
        lastUpdated: exampleDate,
        revision: '2f2932c83b7a401d960f4538bf787e12c44dfd666',
        sourceImage: 'sourceImageA',
        isComparedAgainst: true,
      },
      {
        name: 'cluster-health',
        isFollowingChannel: true,
        channelFollowing: 'testing',
        lastUpdated: exampleDate,
        revision: 'b90s232c83b7a401d960f4538bf787e12c44dfd666',
        sourceImage: 'sourceImageB',
        isComparedAgainst: true,
        isMismatch: true,
      },
      {
        name: 'resource manager',
        isFollowingChannel: true,
        channelFollowing: 'testing',
        lastUpdated: exampleDate,
        revision: 'b90s232c83b7a401d960f4538bf787e12c44dfd666',
        sourceImage: 'sourceImageB',
        isComparedAgainst: true,
      },
      {
        name: 'cluster-service',
        isFollowingChannel: true,
        channelFollowing: 'testing',
        lastUpdated: exampleDate,
        revision: 'b90s232c83b7a401d960f4538bf787e12c44dfd666',
        sourceImage: 'sourceImageB',
        isComparedAgainst: true,
      },
      {
        name: 'extension-catalog-service',
        isFollowingChannel: true,
        channelFollowing: 'testing',
        lastUpdated: exampleDate,
        revision: 'b90s232c83b7a401d960f4538bf787e12c44dfd666',
        sourceImage: 'sourceImageB',
        isComparedAgainst: true,
      },
      {
        name: 'cluster-agent-service',
        isFollowingChannel: true,
        channelFollowing: 'testing',
        lastUpdated: exampleDate,
        revision: 'b90s232c83b7a401d960f4538bf787e12c44dfd666',
        sourceImage: 'sourceImageB',
        isComparedAgainst: true,
      },
      {
        name: 'intent',
        isFollowingChannel: true,
        channelFollowing: 'testing',
        lastUpdated: exampleDate,
        revision: 'b90s232c83b7a401d960f4538bf787e12c44dfd666',
        sourceImage: 'sourceImageB',
        isComparedAgainst: true,
      },
    ],
  },
];
